#!/usr/bin/env bash
set -e

echo "Installing tracev..."

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
TRACEV_DIR="${BASE_DIR}/.tracev"
TRACEV_BIN_DIR="$TRACEV_DIR/bin"

HTML_URL="https://raw.githubusercontent.com/zach030/tracev/v0.0.1/index.html"
HTML_DIR="$TRACEV_DIR/templates"
TARGET_HTML_PATH="$HTML_DIR/index.html"

mkdir -p "$HTML_DIR"
curl -# -L "$HTML_URL" -o "$TARGET_HTML_PATH"

BIN_URL="https://github.com/zach030/tracev/releases/download/v0.0.1/trace_viewer"
BIN_PATH="$TRACEV_BIN_DIR/tracev"

mkdir -p "$TRACEV_BIN_DIR"
curl -# -L "$BIN_URL" -o "$BIN_PATH"
chmod +x "$BIN_PATH"

case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    ;;
*)
    echo "tracev: could not detect shell, manually add ${TRACEV_BIN_DIR} to your PATH."
    exit 1
esac


if [[ ":$PATH:" != *":${TRACEV_BIN_DIR}:"* ]]; then
    echo "export PATH=\"\$PATH:$TRACEV_BIN_DIR\"" >> "$PROFILE"
fi

echo "tracev installed. Please restart your terminal or run 'source ${PROFILE}' to use tracev."
